language: python
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
env:
  - CODECOV_TOKEN="78122297-784f-499a-9ca4-40730d367d06"
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3.5"
sudo: enabled
install:
  - pip install -U setuptools twine wheel flask codecov rsa>=4.0 pycrypto>=2.6.1
  - make dev
script:
  - coverage run setup.py test
after_success:
  - codecov